Nieuwenhuizen:
  ContentSecurityPolicy:
      enabled: true
      content-security-policy:
        default:
          base-uri:
            - "'self'"
          connect-src:
            - "'self'"
          default-src:
            - "'self'"
          form-action:
            - "'self'"
          img-src:
            - "'self'"
          media-src:
            - "'self'"
          frame-src:
            - "'self'"
          object-src:
            - "'self'"
          script-src:
            - "'self'"
            - 'data:'
            - '{nonce}'
          style-src:
            - "'self'"
            - "'unsafe-inline'"
          font-src:
            - "'self'"
